[package]
name = "crab-vault-utils"
version = "0.2.15"
edition = "2024"
description = "All the utils of crab vault"
license = "MIT"
repository = "https://github.com/sylvan-lyon/crab-vault.git"

[dependencies]
